### ISSUE TITLE
[Feature Request] 6xxx support

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/VCEEnc#29]
Hello, I am trying to convert videos using a 6900xt but it seems that everything errors out no matter what is provided, so I assume it is not supported yet? 

```
VCEEncC64.exe --y4m -i test.y4m --vbr 6000 -c hevc -o out.mp4
--------------------------------------------------------------------------------
out.mp4
--------------------------------------------------------------------------------
GPU #0 (AMD Radeon RX 6900 XT) [H.265/HEVC] does not support ouput format NV12.

Finished with error in VCEEncC.


VCEEncC64.exe --y4m -i test.y4m --vbr 6000 -o out.mp4
--------------------------------------------------------------------------------
out.mp4
--------------------------------------------------------------------------------
GPU #0 (AMD Radeon RX 6900 XT) [H.264/AVC] does not support ouput format NV12.

Finished with error in VCEEncC.
```

If I try setting it to 10bit output, it then weirdly complains about input type. 

```
VCEEncC64.exe --y4m -i test.y4m --vbr 6000 -c hevc -o out.mp4 --output-depth 10
--------------------------------------------------------------------------------
out.mp4
--------------------------------------------------------------------------------
GPU #0 (AMD Radeon RX 6900 XT) [H.265/HEVC] does not support input format P010.
```

I have tried with multiple different input types, from this `y4m` file to other `mp4`s using both `--avhw` and `--avsw` with the same results. 

<details> 
<summary>HW Details</summary>

```
VCEEncC (x64) 6.12 by rigaya, build May 23 2021 13:42:37
AMF Version 1.4.18
reader: raw, avs, vpy, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP9, VC-1]
VCE available
device #0: AMD Radeon RX 6900 XT
```
</details>

<details>
<summary>Features</summary>

```
device #0: AMD Radeon RX 6900 XT
H.264/AVC encode features
10bit depth:     no
acceleration:    Hardware-accelerated
max profile:     High
max level:       5.2
max bitrate:     2147483 kbps
ref frames:      1-16
Bframe support:  no
HW instances:    0
max streams:     16
timeout support: yes

H.264/AVC input:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  NV12(native), YUV420P, YV12, BGRA, RGBA, ARGB
memory type: DX11(native), OPENCL, OPENGL, HOST

H.264/AVC output:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  UNKNOWN(native)
memory type: DX11(native), OPENCL, OPENGL, HOST

H.265/HEVC encode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max profile:     main
max level:       6.2
max bitrate:     2147483 kbps
ref frames:      1-16
max streams:     16
timeout support: yes

H.265/HEVC input:
Width:       128 - 8192
Height:      128 - 4352
alignment:   32
Interlace:   no
pix format:  NV12(native), YUV420P, YV12, BGRA, RGBA, ARGB
memory type: DX11(native), OPENCL, OPENGL, HOST

H.265/HEVC output:
Width:       128 - 8192
Height:      128 - 4352
alignment:   32
Interlace:   no
pix format:  UNKNOWN(native)
memory type: DX11(native), OPENCL, OPENGL, HOST



device #0: AMD Radeon RX 6900 XT
H.264/AVC decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

H.264/AVC output:
Width:       32 - 4096
Height:      32 - 4080
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)

H.265/HEVC decode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max streams:     0

H.265/HEVC output:
Width:       32 - 7680
Height:      32 - 4320
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)

MPEG2 decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

MPEG2 output:
Width:       32 - 1920
Height:      32 - 1080
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)

VP9 decode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max streams:     16

VP9 output:
Width:       32 - 7680
Height:      32 - 4320
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)

VC-1 decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

VC-1 output:
Width:       32 - 1920
Height:      32 - 1080
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)
```

</details>

<details><summary>Codecs</summary> 

```
D-: Decode
-E: Encode
---------------------
D- 8svx_exp        : 8SVX exponential
D- 8svx_fib        : 8SVX fibonacci
DE aac             : AAC (Advanced Audio Coding)
D- aac_fixed       : AAC (Advanced Audio Coding)
D- aac_latm        : AAC LATM (Advanced Audio Coding LATM syntax)
DE ac3             : ATSC A/52A (AC-3)
DE ac3_fixed       : ATSC A/52A (AC-3)
D- acelp.kelvin    : Sipro ACELP.KELVIN
D- adpcm_4xm       : ADPCM 4X Movie
DE adpcm_adx       : SEGA CRI ADX ADPCM
D- adpcm_afc       : ADPCM Nintendo Gamecube AFC
D- adpcm_agm       : ADPCM AmuseGraphics Movie
D- adpcm_aica      : ADPCM Yamaha AICA
D- adpcm_argo      : ADPCM Argonaut Games
D- adpcm_ct        : ADPCM Creative Technology
D- adpcm_dtk       : ADPCM Nintendo Gamecube DTK
D- adpcm_ea        : ADPCM Electronic Arts
D- adpcm_ea_maxis_xa: ADPCM Electronic Arts Maxis CDROM XA
D- adpcm_ea_r1     : ADPCM Electronic Arts R1
D- adpcm_ea_r2     : ADPCM Electronic Arts R2
D- adpcm_ea_r3     : ADPCM Electronic Arts R3
D- adpcm_ea_xas    : ADPCM Electronic Arts XAS
D- adpcm_ima_alp   : ADPCM IMA High Voltage Software ALP
D- adpcm_ima_amv   : ADPCM IMA AMV
D- adpcm_ima_apc   : ADPCM IMA CRYO APC
DE adpcm_ima_apm   : ADPCM IMA Ubisoft APM
D- adpcm_ima_cunning: ADPCM IMA Cunning Developments
D- adpcm_ima_dat4  : ADPCM IMA Eurocom DAT4
D- adpcm_ima_dk3   : ADPCM IMA Duck DK3
D- adpcm_ima_dk4   : ADPCM IMA Duck DK4
D- adpcm_ima_ea_eacs: ADPCM IMA Electronic Arts EACS
D- adpcm_ima_ea_sead: ADPCM IMA Electronic Arts SEAD
D- adpcm_ima_iss   : ADPCM IMA Funcom ISS
D- adpcm_ima_mtf   : ADPCM IMA Capcom's MT Framework
D- adpcm_ima_oki   : ADPCM IMA Dialogic OKI
DE adpcm_ima_qt    : ADPCM IMA QuickTime
D- adpcm_ima_rad   : ADPCM IMA Radical
D- adpcm_ima_smjpeg: ADPCM IMA Loki SDL MJPEG
DE adpcm_ima_ssi   : ADPCM IMA Simon & Schuster Interactive
DE adpcm_ima_wav   : ADPCM IMA WAV
D- adpcm_ima_ws    : ADPCM IMA Westwood
DE adpcm_ms        : ADPCM Microsoft
D- adpcm_mtaf      : ADPCM MTAF
D- adpcm_psx       : ADPCM Playstation
D- adpcm_sbpro_2   : ADPCM Sound Blaster Pro 2-bit
D- adpcm_sbpro_3   : ADPCM Sound Blaster Pro 2.6-bit
D- adpcm_sbpro_4   : ADPCM Sound Blaster Pro 4-bit
DE adpcm_swf       : ADPCM Shockwave Flash
D- adpcm_thp       : ADPCM Nintendo THP
D- adpcm_thp_le    : ADPCM Nintendo THP (little-endian)
D- adpcm_vima      : LucasArts VIMA audio
D- adpcm_xa        : ADPCM CDROM XA
DE adpcm_yamaha    : ADPCM Yamaha
D- adpcm_zork      : ADPCM Zork
DE alac            : ALAC (Apple Lossless Audio Codec)
D- als             : MPEG-4 Audio Lossless Coding (ALS)
D- amrnb           : AMR-NB (Adaptive Multi-Rate NarrowBand)
D- amrwb           : AMR-WB (Adaptive Multi-Rate WideBand)
D- ape             : Monkey's Audio
DE aptx            : aptX (Audio Processing Technology for Bluetooth)
DE aptx_hd         : aptX HD (Audio Processing Technology for Bluetooth)
D- ass             : ASS (Advanced SubStation Alpha) subtitle
D- atrac1          : ATRAC1 (Adaptive TRansform Acoustic Coding)
D- atrac3          : ATRAC3 (Adaptive TRansform Acoustic Coding 3)
D- atrac3al        : ATRAC3 AL (Adaptive TRansform Acoustic Coding 3 Advanced Lossless)
D- atrac3plus      : ATRAC3+ (Adaptive TRansform Acoustic Coding 3+)
D- atrac3plusal    : ATRAC3+ AL (Adaptive TRansform Acoustic Coding 3+ Advanced Lossless)
D- atrac9          : ATRAC9 (Adaptive TRansform Acoustic Coding 9)
D- bmv_audio       : Discworld II BMV audio
D- cc_dec          : Closed Caption (EIA-608 / CEA-708)
DE comfortnoise    : RFC 3389 comfort noise generator
D- cook            : Cook / Cooker / Gecko (RealAudio G2)
DE dca             : DCA (DTS Coherent Acoustics)
D- derf_dpcm       : DPCM Xilam DERF
D- dolby_e         : Dolby E
D- dsd_lsbf        : DSD (Direct Stream Digital), least significant bit first
D- dsd_lsbf_planar : DSD (Direct Stream Digital), least significant bit first, planar
D- dsd_msbf        : DSD (Direct Stream Digital), most significant bit first
D- dsd_msbf_planar : DSD (Direct Stream Digital), most significant bit first, planar
D- dsicinaudio     : Delphine Software International CIN audio
D- dss_sp          : Digital Speech Standard - Standard Play mode (DSS SP)
D- dst             : DST (Digital Stream Transfer)
D- dvaudio         : Ulead DV Audio
D- dvbsub          : DVB subtitles
D- dvdsub          : DVD subtitles
DE eac3            : ATSC A/52 E-AC-3
D- evrc            : EVRC (Enhanced Variable Rate Codec)
DE flac            : FLAC (Free Lossless Audio Codec)
DE g722            : G.722 ADPCM
DE g723_1          : G.723.1
DE g726            : G.726 ADPCM
DE g726le          : G.726 little endian ADPCM ("right-justified")
D- g729            : G.729
D- gremlin_dpcm    : DPCM Gremlin
D- gsm             : GSM
D- gsm_ms          : GSM Microsoft variant
D- hca             : CRI HCA
D- hcom            : HCOM Audio
D- iac             : IAC (Indeo Audio Coder)
D- ilbc            : iLBC (Internet Low Bitrate Codec)
D- imc             : IMC (Intel Music Coder)
D- interplay_dpcm  : DPCM Interplay
D- interplayacm    : Interplay ACM
D- jacosub         : JACOsub subtitle
D- libaribb24      : libaribb24 ARIB STD-B24 caption decoder
-E libmp3lame      : libmp3lame MP3 (MPEG audio layer 3)
DE libopus         : libopus Opus
DE libspeex        : libspeex Speex
-E libtwolame      : libtwolame MP2 (MPEG audio layer 2)
DE libvorbis       : libvorbis
-E libwavpack
D- mace3           : MACE (Macintosh Audio Compression/Expansion) 3:1
D- mace6           : MACE (Macintosh Audio Compression/Expansion) 6:1
D- metasound       : Voxware MetaSound
D- microdvd        : MicroDVD subtitle
DE mlp             : MLP (Meridian Lossless Packing)
D- mov_text        : 3GPP Timed Text subtitle
D- mp1             : MP1 (MPEG audio layer 1)
D- mp1float        : MP1 (MPEG audio layer 1)
DE mp2             : MP2 (MPEG audio layer 2)
-E mp2fixed        : MP2 fixed point (MPEG audio layer 2)
D- mp2float        : MP2 (MPEG audio layer 2)
D- mp3             : MP3 (MPEG audio layer 3)
D- mp3adu          : ADU (Application Data Unit) MP3 (MPEG audio layer 3)
D- mp3adufloat     : ADU (Application Data Unit) MP3 (MPEG audio layer 3)
D- mp3float        : MP3 (MPEG audio layer 3)
D- mp3on4          : MP3onMP4
D- mp3on4float     : MP3onMP4
D- mpc7            : Musepack SV7
D- mpc8            : Musepack SV8
D- mpl2            : MPL2 subtitle
DE nellymoser      : Nellymoser Asao
D- on2avc          : On2 Audio for Video Codec
DE opus            : Opus
D- paf_audio       : Amazing Studio Packed Animation File Audio
DE pcm_alaw        : PCM A-law / G.711 A-law
D- pcm_bluray      : PCM signed 16|20|24-bit big-endian for Blu-ray media
DE pcm_dvd         : PCM signed 16|20|24-bit big-endian for DVD media
D- pcm_f16le       : PCM 16.8 floating point little-endian
D- pcm_f24le       : PCM 24.0 floating point little-endian
DE pcm_f32be       : PCM 32-bit floating point big-endian
DE pcm_f32le       : PCM 32-bit floating point little-endian
DE pcm_f64be       : PCM 64-bit floating point big-endian
DE pcm_f64le       : PCM 64-bit floating point little-endian
D- pcm_lxf         : PCM signed 20-bit little-endian planar
DE pcm_mulaw       : PCM mu-law / G.711 mu-law
DE pcm_s16be       : PCM signed 16-bit big-endian
DE pcm_s16be_planar: PCM signed 16-bit big-endian planar
DE pcm_s16le       : PCM signed 16-bit little-endian
DE pcm_s16le_planar: PCM signed 16-bit little-endian planar
DE pcm_s24be       : PCM signed 24-bit big-endian
DE pcm_s24daud     : PCM D-Cinema audio signed 24-bit
DE pcm_s24le       : PCM signed 24-bit little-endian
DE pcm_s24le_planar: PCM signed 24-bit little-endian planar
DE pcm_s32be       : PCM signed 32-bit big-endian
DE pcm_s32le       : PCM signed 32-bit little-endian
DE pcm_s32le_planar: PCM signed 32-bit little-endian planar
DE pcm_s64be       : PCM signed 64-bit big-endian
DE pcm_s64le       : PCM signed 64-bit little-endian
DE pcm_s8          : PCM signed 8-bit
DE pcm_s8_planar   : PCM signed 8-bit planar
DE pcm_u16be       : PCM unsigned 16-bit big-endian
DE pcm_u16le       : PCM unsigned 16-bit little-endian
DE pcm_u24be       : PCM unsigned 24-bit big-endian
DE pcm_u24le       : PCM unsigned 24-bit little-endian
DE pcm_u32be       : PCM unsigned 32-bit big-endian
DE pcm_u32le       : PCM unsigned 32-bit little-endian
DE pcm_u8          : PCM unsigned 8-bit
DE pcm_vidc        : PCM Archimedes VIDC
D- pgssub          : HDMV Presentation Graphic Stream subtitles
D- pjs             : PJS subtitle
D- qcelp           : QCELP / PureVoice
D- qdm2            : QDesign Music Codec 2
D- qdmc            : QDesign Music Codec 1
D- ralf            : RealAudio Lossless
DE real_144        : RealAudio 1.0 (14.4K)
D- real_288        : RealAudio 2.0 (28.8K)
D- realtext        : RealText subtitle
DE roq_dpcm        : id RoQ DPCM
DE s302m           : SMPTE 302M
D- sami            : SAMI subtitle
DE sbc             : SBC (low-complexity subband codec)
D- sdx2_dpcm       : DPCM Squareroot-Delta-Exact
D- shorten         : Shorten
D- sipr            : RealAudio SIPR / ACELP.NET
D- siren           : Siren
D- smackaud        : Smacker audio
D- sol_dpcm        : DPCM Sol
DE sonic           : Sonic
-E sonicls         : Sonic lossless
D- srt             : SubRip subtitle
D- ssa             : ASS (Advanced SubStation Alpha) subtitle
D- stl             : Spruce subtitle format
D- subrip          : SubRip subtitle
D- subviewer       : SubViewer subtitle
D- subviewer1      : SubViewer1 subtitle
D- tak             : TAK (Tom's lossless Audio Kompressor)
D- text            : Raw text subtitle
DE truehd          : TrueHD
D- truespeech      : DSP Group TrueSpeech
DE tta             : TTA (True Audio)
D- twinvq          : VQF TwinVQ
D- vmdaudio        : Sierra VMD audio
-E vorbis          : Vorbis
D- vplayer         : VPlayer subtitle
D- wavesynth       : Wave synthesis pseudo-codec
DE wavpack         : WavPack
D- webvtt          : WebVTT subtitle
D- wmalossless     : Windows Media Audio Lossless
D- wmapro          : Windows Media Audio 9 Professional
DE wmav1           : Windows Media Audio 1
DE wmav2           : Windows Media Audio 2
D- wmavoice        : Windows Media Audio Voice
D- ws_snd1         : Westwood Audio (SND1)
D- xan_dpcm        : DPCM Xan
D- xma1            : Xbox Media Audio 1
D- xma2            : Xbox Media Audio 2
D- xsub            : DivX subtitles (XSUB)
```
</details>

If you need any more details or testing done just let me know.

Edit: I have tested with ffmpeg and OBS and the AMF encoders on the card are working as expected.

**Comment by Napatt** [comment]
That's an issue on AMD driver v21.6.1 & v21.6.2. (JUL-2021) Rollback to v21.5.2 should fix that.

**Comment by cdgriffith** [comment]
Hey, rolling back did work, thanks @Napatt! 

But is it a driver bug or this software?  Because `ffmpeg` and other hardware encoders still worked. I also tried today's latest `21.7.1` and it didn't work either and I don't see any listed known issue for it.

**Comment by cdgriffith** [comment]
Possibly even a re-compile with latest AMF (released 10 days ago) might help? https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v.1.4.21

**Comment by cdgriffith** [comment]
Had to upgrade back to `21.7.1` because latest `FFmpeg` does not work at all with AMF encoder on `21.5.2` it seems. So I doubt it's a "driver issue", as much as some API missmatch or something.

**Comment by cdgriffith** [comment]
I have tried downloading latest AMF `1.4.21`  from [their releases](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v.1.4.21) (as it does not match up with their actual source code), as well as [updated the submodules](https://github.com/cdgriffith/VCEEnc/blob/master/appveyor.yml#L27) and did a debug build and the error remains the same: 

https://ci.appveyor.com/project/cdgriffith/vceenc/builds/40051287

**Comment by GlitterKill** [comment]
I am having the same problem.  5700 XT with 21.6.1 drivers getting the same error "[H.265/HEVC] does not support ouput format NV12."

**Comment by elemelek** [comment]
Same problem here. RX 6800. Had to downgrade to 21.5.2.

**Comment by GlitterKill** [comment]
I was not able to downgrade without extra effort.  I tried the 21.7.2 release from yesterday and it has the same issue as well.

**Comment by GlitterKill** [comment]
Little more info.  I did a check for GPU features with 21.7.2 installed and this is what I got:

device #0: AMD Radeon RX 5700 XT
H.264/AVC encode features
10bit depth:     no
acceleration:    Hardware-accelerated
max profile:     High
max level:       5.2
max bitrate:     2147483 kbps
ref frames:      1-16
Bframe support:  no
HW instances:    0
max streams:     16
timeout support: yes

H.264/AVC input:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  NV12(native), YUV420P, YV12, BGRA, RGBA, ARGB
memory type: DX11(native), OPENCL, OPENGL, HOST

H.264/AVC output:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  UNKNOWN(native)
memory type: DX11(native), OPENCL, OPENGL, HOST

H.265/HEVC encode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max profile:     main
max level:       6.2
max bitrate:     2147483 kbps
ref frames:      1-16
max streams:     16
timeout support: yes

H.265/HEVC input:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  NV12(native), YUV420P, YV12, BGRA, RGBA, ARGB
memory type: DX11(native), OPENCL, OPENGL, HOST

H.265/HEVC output:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  Unexpected(native), Unexpected(native)
memory type: DX11(native), OPENCL, OPENGL, HOST



device #0: AMD Radeon RX 5700 XT
H.264/AVC decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

H.264/AVC output:
Width:       32 - 4096
Height:      32 - 4080
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)

H.265/HEVC decode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max streams:     0

H.265/HEVC output:
Width:       32 - 7680
Height:      32 - 4320
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)

MPEG2 decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

MPEG2 output:
Width:       32 - 1920
Height:      32 - 1080
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)

VP9 decode features
10bit depth:     yes
acceleration:    Hardware-accelerated
max streams:     16

VP9 output:
Width:       32 - 7680
Height:      32 - 4320
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)

VC-1 decode features
10bit depth:     no
acceleration:    Hardware-accelerated
max streams:     16

VC-1 output:
Width:       32 - 1920
Height:      32 - 1080
alignment:   32
Interlace:   yes
pix format:  NV12(native), BGRA, RGBA
memory type: DX11(native)


So it looks like the problems are coming from

H.265/HEVC output:
Width:       128 - 4096
Height:      128 - 4096
alignment:   32
Interlace:   no
pix format:  Unexpected(native), Unexpected(native)
memory type: DX11(native), OPENCL, OPENGL, HOST


I am looking to see if there is a way to specify a different pix format or output format as a possible workaround but have not found a way to do that yet.  Anyone else know?

**Comment by elemelek** [comment]
I found that the GetFormatAt() does not return proper values for encode features. As it is part of AMF components should this be AMF issue?

**Comment by rigaya** [comment]
VCEEnc as calling GetFormatAt to check whether the GPU supports the expected format or not, but I also checked GetFormatAt and was not setting proper value for input/output formats in recent drivers (including the latest 21.7.2). There might be some problem in AMF (or driver).

[VCEEnc 6.13](https://github.com/rigaya/VCEEnc/releases/tag/6.13) will stop checking these input/output formats to avoid running into errors.

**Comment by elemelek** [comment]
VCEEnc 6.13 works with 21.7.2 drivers. Thanks you!

**Comment by cdgriffith** [comment]
Tested with AVC and 10-bit HDR10 HEVC, working great with drivers 21.7.2, thank you!
